name: Remove Themes and Upload os-release

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Remove Themes
        run: sudo rm -rf /usr/share/themes  # Deletes themes

      - name: Upload os-release File
        uses: actions/upload-artifact@v4
        with:
          name: os-release
          path: /etc/os-release
